version: '3.8'
services:
  apache-php:
    build: ./apache-php
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql  # Volumen persistente para los datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialización
    ports:
      - "3306:3306"

volumes:
  mysql-data: {}